name: Notify Discord on push
on:
  push:
    branches: [ "**" ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" -X POST -d "{\"content\":\"📢 Push in **${{ github.repository }}** von **${{ github.actor }}**\\n${{ github.event.head_commit.message }}\\nhttps://github.com/${{ github.repository }}/commit/${{ github.sha }}\"}" \"$DISCORD_WEBHOOK\"
