name: Notify Discord on push
on:
  push:
    branches: [ "**" ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    run: |
  MESSAGE="📢 Push in **${GITHUB_REPOSITORY}** von **${GITHUB_ACTOR}**"
  curl -H "Content-Type: application/json" -X POST -d "{\"content\":\"$MESSAGE\"}" "$DISCORD_WEBHOOK"
